/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const FilmTi = t.iface([], {
  "awardsSummary": t.union("null", "string"),
  "backdropUrl": t.union("null", "string"),
  "budget": t.union("null", "string"),
  "cast": t.array("string"),
  "countriesOfOrigin": t.array("string"),
  "director": t.union("null", "string"),
  "genres": t.array("string"),
  "homepage": t.union("null", "string"),
  "id": "number",
  "keywords": t.array("string"),
  "language": t.union("null", "string"),
  "languages": t.array("string"),
  "originalTitle": t.union("null", "string"),
  "plot": t.union("null", "string"),
  "posterUrl": t.union("null", "string"),
  "production": t.union("null", "string"),
  "releaseDate": t.union("null", "string"),
  "releaseYear": t.union("null", "number"),
  "revenue": t.union("null", "string"),
  "runtime": t.union("null", "number"),
  "searchL": t.union("null", "string"),
  "status": t.union("null", "string"),
  "title": t.union("null", "string"),
  "tmdbRating": t.union("null", "number"),
  "trailerUrl": t.union("null", "string"),
  "trailerYouTubeId": t.union("null", "string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  FilmTi,
};
export default exportedTypeSuite;
